To discover Jeedom you can also run in a Docker container :

[IMPORTANT]
Prerequisite: Having a machine or a VM running Linux

=== Step 1 : Installation of Docker

docker is now available on all recent distributions. To install on a distribution

* rpm based 
----
$ yum install docker
----

* deb based
----
$ apt-get update
$ apt-get install docker
$ apt-get install docker.io
----

==== Step 2 : Download the image of the container Jeedom

To use Jeedom, we must firstly download the image that will be used to launch the container.

----
$ docker pull cquad/jeedom
----

One can then check that the image is available :

---- 
$ docker images
----

This command should display a line with us cquad/jeedom.
----
REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
cquad/jeedom        latest              9a18afc80af8        3 months ago        580.7 MB
----

=== Step 3 : Launching the container

We will now start the container :

----
$ docker run --name jeedom -p 22 -p 80 -p 9001 cquad/jeedom
----
This command will launch a container named jeedom which is based on the image cquad/jeedom
The -p option can expose a port of the container, in our case it is the port for ssh, and jeedom supervisor

[IMPORTANT]
the ssh service, jeedom and supervisor are not accessible on 22,80 port and 9001. They are published on other ports.

To verify that the container is running well and know the port through which access jeedom :

----
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS                                                                     NAMES
0fc1a4f3f584        cquad/jeedom:latest   "/usr/bin/supervisor   About an hour ago   Up About an hour    0.0.0.0:49153->22/tcp, 0.0.0.0:49154->80/tcp, 0.0.0.0:49155->9001/tcp   jeedom
----

In this example jeedom is available at the following address 'http://ip_server:49154/

[TIP]
If you need to connect a device to your container, it is necessary to launch the container to add the option --device=chemin_host:chemin_conteneur. for example --device=/dev/ttyS0:/dev/ttyS0


SSH identifier are 
--
- User : root
- Password : jeedom
--


For the rest you can follow the documentation https://www.jeedom.fr/doc/documentation/premiers-pas/en_US/doc-premiers-pas.html[Getting Started with Jeedom]